# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bubble_sensor_gpio', models.SmallIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerstats.Brew')),
            ],
        ),
    ]
