# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
